apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8snamespacepattern
  annotations:
    metadata.gatekeeper.sh/title: "Namespace Naming Convention"
    metadata.gatekeeper.sh/version: 1.0.0
    description: >-
      Enforces the naming convention for Kubernetes namespaces as <Team_Name>_<App_Name>_<Environment>.
spec:
  crd:
    spec:
      names:
        kind: K8sNamespacePattern
      validation:
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
            pattern:
              type: string
              description: >-
                The regular expression pattern to match the namespace name against.

  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snamespacepattern

        get_message(parameters, _default) = msg {
          not parameters.message
          msg := _default
        }

        get_message(parameters, _default) = msg {
          msg := parameters.message
        }

        violation[{"msg": msg}] {
          not re_match(input.parameters.pattern, input.review.object.metadata.name)
          def_msg := sprintf("Namespace name <%v> does not match required pattern <%v>", [input.review.object.metadata.name, input.parameters.pattern])
          msg := get_message(input.parameters, def_msg)
        }